### PR TITLE
Add python agent support

### PR DESCRIPTION
**Pull request by jamescarr**
I had this PR against @sivel's repository but he deleted it (I guess it was a fork and I didn't realize it).

Here the PR is, applied again.

### CODE REVIEW

**Comment by toshitanian** [comment]
@jamescarr  sorry, this repo is fork of original repo.

**Comment by jamescarr** [comment]
@kawasakitoshiya oh... where is the original repo?

**Comment by toshitanian** [comment]
I guess @sivel had original repo, but he deleted it.
Why don't you host the `ansible-newrelic`?

**Comment by jamescarr** [comment]
Hmmm I actually rewrote our ansible role from the ground up. I'll spawn a new repo when I get time.

**Pull request closed without merging**
